# Generated by Django 5.0.6 on 2026-04-02 06:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('photo', 'Photo')], max_length=10)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='posts/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/')),
                ('caption', models.TextField(blank=True, max_length=2200)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('saves_count', models.PositiveIntegerField(default=0)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('published', 'Published'), ('removed', 'Removed')], default='published', max_length=20)),
                ('is_comments_disabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
